# Generated by Django 3.2.8 on 2021-11-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_thumbanil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbanil',
            new_name='thumbnail',
        ),
    ]
